
name: 'hubspot_source_integration_tests'
version: '0.3.2'
profile: 'integration_tests'
config-version: 2

models:
  hubspot_source:
    +schema: staging

vars:
  hubspot_source:
    hubspot_database: raw
    hubspot_schema: raw_fivetran_hubspot
    hubspot_service_enabled: true
